name: notiq
description: Notiq - Smart notes app with dark mode and custom colors
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  outline_material_icons: ^1.0.0
  sqflite: ^2.4.2
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  share_plus: ^7.2.1
  provider: ^6.0.5
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_foreground: "assets/icon/logo_foreground.png"
  adaptive_icon_background: "#ffffff"



flutter:
  uses-material-design: true




